<?php

namespace AppBundle\Repository;

/**
 * BargainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BargainRepository extends \Doctrine\ORM\EntityRepository
{
}
